name: Build and Test

on:
  push:
    branches: [ main, copilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Services
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Build tools
      run: make setup
    
    - name: Generate protobuf code for all services
      run: make proto-all
    
    - name: Run tests
      run: make test

  build:
    name: Build Services
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [example-service, health-service, user-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Build tools
      run: make setup
    
    - name: Generate protobuf code for all services
      run: make proto-all
    
    - name: Build service for multiple architectures
      run: make build-multiarch SERVICE=${{ matrix.service }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-binaries
        path: |
          bin/${{ matrix.service }}-linux-amd64
          bin/${{ matrix.service }}-linux-arm64
        retention-days: 7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: make docker-build SERVICE=${{ matrix.service }}
    
    - name: Save Docker image
      run: docker save ${{ matrix.service }}:latest | gzip > ${{ matrix.service }}-image.tar.gz
    
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-docker-image
        path: ${{ matrix.service }}-image.tar.gz
        retention-days: 7
